# Version of docker-compose.
version: '3'

# Containers we're going to run.
services:
    # Our Phoenix container.
    phoenix:
        # The build parameters for this container.
        build:
            # Here we define that it should build from the current directory.
            context: .
        environment:
            # Variables to connect to our Postgres server.
            PGUSER: postgres
            PGPASSWORD: postgres
            PGDATABASE: test_chat
            PGPORT: 5432
            # Hostname of our Postgres container.
            PGHOST: db
            POOL_SIZE: 10
            MIX_ENV: dev
        ports:
            # Mapping the port to make the Phoenix app accessible outside of the container.
            - '4000:4000'
        networks:
            - default
        depends_on:
            # The DB container needs to be started before we start this container.
            - db
        volumes:
            - ./:/app
    db:
        # We use the predefined Postgres image.
        image: postgres:9.6
        environment:
            # Set user/password for Postgres.
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            # Set a path where Postgres should store the data.
            PGDATA: /var/lib/postgresql/data/pgdata
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
# Define the volumes.
volumes:
    pgdata:
